### ISSUE TITLE
Implement stylechecks

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/lattice-surgery-compiler#101]
Stylecheck (black, isort, flake8 , mypy) on current code as well as setup automate style check for future pull request

**Comment by alexnguyenn** [comment]
Update on progress:
* `black` was done with #129 
* `mypy` was done with #136 
* configs for those tools will be added in #137

**Comment by gwwatkin** [comment]
@mstechly, @ntwalibas, @pediejo Update on the style checks and static analysis we discussed. Preparing to move towards automation.

**Comment by alexnguyenn** [comment]
Final update:
* `flake8` and `isort` done on https://github.com/latticesurgery-com/lattice-surgery-compiler/pull/139
* Add `pre-commit` in https://github.com/latticesurgery-com/lattice-surgery-compiler/pull/143

We choose to use [pre-commit.ci](https://pre-commit.ci/) as automated check due to the minimal configuration required (only [`.pre-commit-config.yaml`](https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/dev/.pre-commit-config.yaml)) and great run time - see #144 for a sample run. We will implement automated testing with Github Actions once #100 is done.

**Comment by gwwatkin** [comment]
@mstechly, @ntwalibas, @pediejo

**Comment by mstechly** [comment]
Awesome!
