### ISSUE TITLE
Reorganize the compiler directory

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/lattice-surgery-compiler#114]
As we want to publish the compiler to [PyPI](https://pypi.org/), I suggest that we start to refactor/restructure our compiler repository to be the same as an Python package. This should start after we are done with https://github.com/latticesurgery-com/lattice-surgery-compiler/issues/99 and before any development happens on the compiler. 
 
Some links to look at (for reference) : 
- https://docs.python-guide.org/writing/structure/
- https://packaging.python.org/tutorials/packaging-projects/
- https://sphinx-rtd-tutorial.readthedocs.io/en/latest/folders.html

**Comment by alexnguyenn** [comment]
We can also look how other related libraries setup their repositories: 
- https://github.com/Quantomatic/pyzx
- https://github.com/oscarhiggott/PyMatching

Feel free to add suggestions below.

**Comment by alexnguyenn** [comment]
Also an excellent example from Unitary Fund's Mitiq repo: https://github.com/unitaryfund/mitiq

**Comment by gwwatkin** [comment]
I also suggest renaming:
 * `Circuit` -> `CircuitOfPauliRotations`
 * `Rotation` -> `PauliRotation`

**Comment by alexnguyenn** [comment]
I think `CircuitOfPauliRotations` is too long. Maybe something like `PauliCircuit`?

**Comment by gwwatkin** [comment]
I'm trying to look at it from the point of view of someone who is trying to understand our code, having just looked at it with someone who was puzzled by why a quiskit circuit becomes another `Circuit`. Getting Pauli in is enough to solve that problem. But think of this: if I see a method that returns ` -> CircuitOfPauliRotations` I immediately have an idea of what that is. If I read `-> PauliCircuit` for the first time, what will I think about? A Google search for Pauli Circuit doesn't return much

**Comment by alexnguyenn** [comment]
Changing name of the issue to fit what we are doing

**Comment by alexnguyenn** [comment]
Here is a preview into the new structure of the repo
```
lattice-surgery-compiler/
├── assets/ 
├── tests/
├── debug/
├── docs/
├── web/ (django, we will scrap this later)
├── webapi/
├── webgui/ (visualizer, we will also scrap this later)
├── src/ (compiler code, name will be updated later)
├── requirements.txt
├── README.md
├── .gitignore
├── setup.py
├── LICENSE
└── .....
```

**Comment by alexnguyenn** [comment]
And inside the `src/` folder:
```
src/
├── pauli_rotations/
│   ├── circuit.py
│   ├── rotation.py
│   └── segmented_qasm_parser.py
├── logical_lattice_ops/
│   ├── logical_lattice_ops.py
│   ├── dependency_graph.py
│   └── visual_array_cell.py
├── patches/
│   ├── patches.py
│   ├── ancilla_region_routing.py
│   └── lattice_surgery_computation_composer.py
├── lattice_array/
│   ├── sparse_lattice_to_array.py
│   └── lattice_surgery_computation_composer.py
├── simulation/
│   ├── qubit_state.py
│   ├── qiskit_opflow_utils.py
│   ├── logical_patch_state_simulation.py
│   └── conditional_operation_control.py
├── pipeline/
│   ├── lattice_surgery_compilation_pipeline.py
│   └── json_pipeline.py (previously in webapi)
└── utils.py
```

**Comment by alexnguyenn** [comment]
See the [reorgranize-repo](https://github.com/latticesurgery-com/lattice-surgery-compiler/tree/reorganize-repo) branch for the current progress on this issue
