### ISSUE TITLE
Adding Contribution Guide

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/lattice-surgery-compiler#117]
See: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by gwwatkin** [comment]
Things to add:
  * `feature_branch -> dev -> master/main` workflow
  * One approval required
  * [...]

**Comment by gwwatkin** [comment]
NOTE: Remember to move the dev setup guide here, from the README

**Comment by alexnguyenn** [comment]
@gwwatkin I think you can take on this since you already wrote the contribution part in our `README`.

[Here is an example](https://github.com/unitaryfund/mitiq/blob/master/CONTRIBUTING.md) from UF's `mitiq`, but there are many templates available online that we could use.

**Comment by alexnguyenn** [comment]
Completed with #154
