### ISSUE TITLE
Auto deploy `dev` to `beta.latticesurgery.com` and `master` to `latticesurgery.com`

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#125]

**Comment by alexnguyenn** [comment]
@gwwatkin wait isn't this what we just did over [web-ui](https://github.com/latticesurgery-com/web-ui)? Can we close it?

**Comment by gwwatkin** [comment]
Yep! Just to `dev` instead of `beta`

**Comment by gwwatkin** [comment]
Actually we don't have dev in our workflow for the webapp, since it's a webapp, we just have continuous integration with `main`, requiring manual approval to propagate changes from `dev.latticesurgery.com` to `latticesurgery.com`
