### ISSUE TITLE
[BUG] Commutations between PauliRotation and Measurement

### ISSUE THREAD

**Issue by isolatedinformation** [latticesurgery-com/lattice-surgery-compiler#156]
Issue Description
-----------------

The commutations rules from Litinski Fig 4. are implemented incorrectly for commutations between PauliRotation block and Measurement block.

How to Reproduce
----------------
Run `tests/pauli_rotations/circuit_test.py::test_apply_transformation()`
The third fixture should fail. 

Problems
-------------
- For the two cases: P and Q commute and P and Q anticommute:
    - [ ] how do exp(i*pi/4*P) and exp(i*pi/4*theta) commute? 
    - [ ] how do exp(i*pi/4*P) and M_{Q} commute? What are the readout distributions?
    - [ ] how do exp(i*pi/4*P) and M_{-Q} commute? What are the readout distributions?
- What about the negative cases like exp(-i*pi/4*P)?
    - [ ] Do we just use exp(-i*pi/4*P) = exp(i*pi*7/4*P)^7 = exp(i*pi/4*P)^7 (sequential application 7 times?)

To-Do
--------
- [ ] Break `commute_pi_over_four_rotations()` into small helper functions for different commutation rules
- [ ] Refactor `apply_transformation()` to adjust for the changes above
- [ ] Tests for the helper functions

**Comment by gwwatkin** [comment]
For the negative cases
> Do we just use exp(-ipi/4P) = exp(ipi7/4P)^7 = exp(ipi/4*P)^7 (sequential application 7 times?)

It worked in the case when commuting with other rotations (from https://github.com/latticesurgery-com/lattice-surgery-compiler/pull/29#discussion_r584187612), see below:

**Note** that the anti commuting case still needs to be checked, but this approach might serve as inspiration.

![00336F56-A85A-4B27-98D3-1FB741B3EA35](https://user-images.githubusercontent.com/36427091/109399510-83722e00-7943-11eb-89bc-0a31b1da7d73.png)

**Comment by gwwatkin** [comment]
Do the rules in (a) also apply to (b)? I.e. can we commute measurements the same way we commute Pauli rotations?
![Screenshot_20211118_101550](https://user-images.githubusercontent.com/36427091/142473214-938187b3-6e4b-485a-9f1d-b77b791df1da.png)

Litinski does it in his presentation.

![Screenshot_20211118_101638](https://user-images.githubusercontent.com/36427091/142473354-adf31662-ef4f-4fd8-9bcb-b76c8b03183a.png)

**Comment by alexnguyenn** [comment]
After today's discussion. I think that we should take a test-driven approach for refactoring `commute_pi_over_four_rotation()` and ignore the existing code. We will write the test cases first (with proofs) and then rewrite the method (even divide it to smaller pieces if we need to).

**Comment by gwwatkin** [comment]
It's starting to sound like the best approach :sweat:

I would also like to have all the cases written out in Latex, so that on a paper we can have an appendix with how all of these things work and maybe add them to the doc. I hope to find the time to do it myself soon, otherwise I'm happy to work with @isolatedinformation and @alexnguyenn  on Overleaf

**Comment by alexnguyenn** [comment]
@gwwatkin sounds good - I think with myst-parser you can use Latex math syntax ([see here](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html?highlight=latex#direct-latex-math)), which will make it easy for us to put them into our documentation.

I would like to implement the test cases and then the rewriting myself after you guys are done with creating those cases.

**Comment by isolatedinformation** [comment]
Let's do a test-based approach. A little extra time now would go a long way. I'm also for making the equations in LaTeX. I'd be happy to work on OverLeaf. I'll get started with some today and share the OverLeaf link on Slack.

**Comment by alexnguyenn** [comment]
So from the test results from #177, seems like the current implementation works. Though should we consider breaking down the commuting method into smaller sections to make it more readable?

**Comment by isolatedinformation** [comment]
Yeah I agree. The method `commute_pi_over_four_rotation` should have a better name. Something like would be good I think
```
def swap_blocks(block1, block2):
     raise Exceptions
     if blocks commute then
           swap_commuting_blocks(block1, block2)
    else
          swap_anticommuting_blocks(block1, block2)
```
Since the logic for (rotation, rotation) and (rotation, measurement) are same, the respective `swap` functions should handle it two if cases. We can `reorder` instead of `swap` or some other word. I do not think it should be commute as it can misleading

**Comment by isolatedinformation** [comment]
#179 - I made a pr for this change

**Comment by isolatedinformation** [comment]
## Litinski's Transform when the circuit has non-consecutive measurements
![image](https://user-images.githubusercontent.com/27089492/144464940-1149f947-7d0e-4f00-ae44-9eb173e73780.png)

This is what happens right now when applying the transformation! Right now the `pop()` of pi/4 assumes that it is last the operation when popping!  Is that pop valid if it is last operation given there are only pi/4 rotations remaining at the end of the circuit, like in the last set of opertions ! Can we still pop them? 

What happens now for different types of circuits! 
![image](https://user-images.githubusercontent.com/27089492/144466156-aa84d9b9-c3ae-43b5-b230-394fd380a75d.png)
![image](https://user-images.githubusercontent.com/27089492/144466213-0b730360-aa80-4457-8bb9-ab52caa660e5.png)
![image](https://user-images.githubusercontent.com/27089492/144466251-fed3a56a-ff0f-4522-978c-dae50b947845.png)

**Comment by alexnguyenn** [comment]
Closing this as #179 is merged. For the issue with the transformation, @isolatedinformation you can make a new issue regarding that.
