### ISSUE TITLE
[BUG] Take in account isNegative during simulation of measurements

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#164]
Currently the isNegative flag is ignored but it has the effect of inverting the measurement outcome
https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/c78c4fdfff645a8ca52c8a8fc2344f18d383aba0/src/lsqecc/simulation/logical_patch_state_simulation.py#L233-L245

**Comment by isolatedinformation** [comment]
The orientation of measurement is truncated out in llops. Exactly in the function, `circuit_to_patch_measurement`
https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/c5c972e4b335e971eb11543e0be67c8f9bade571/src/lsqecc/logical_lattice_ops/logical_lattice_ops.py#L120-L131

The `isNegative` attribute is just dropped out of computation. Need to add code to include that attribute.

**Comment by gwwatkin** [comment]
Looks like it just needs to be added to `SinglePatchMeasurement` and `MultiBodyMeasurement`

**Comment by isolatedinformation** [comment]
#224 partially fixes this issue. need to ensure inclusion in `simulation/` after #219 is closed.
