### ISSUE TITLE
Test `dependency_graph.py`

### ISSUE THREAD

**Issue by alexnguyenn** [latticesurgery-com/lattice-surgery-compiler#172]
As title. Expected to be painful since I don't recall how I implemented it.

**Comment by gwwatkin** [comment]
The purpose was to introduce a dependency DAG of Pauli operations so that we could execute in parallel as many as possible. Might be some time until we start using it ... I'm inclined to defer this to later.

@alexnguyenn , regardless, I'm happy to help create some test cases

**Comment by gwwatkin** [comment]
If you choose to merge you can just move #173 to the backlog
