### ISSUE TITLE
[BUG] Cannot decompose arbitrary Z rotations to Clifford+T

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#233]
Issue Description
-----------------
For example, cannot decompose a pi/16 rotation about Z. This makes it impossible to run a QFT, making it difficult to run any useful benchmark (like in #228)

How to Reproduce
----------------

1. Cherry-pick [this commit](https://github.com/latticesurgery-com/lattice-surgery-compiler/commit/45f84cbd0670c2eafeff3e972f8af3f554dcf12f) to fix the fact that pyzx has trouble parsing circuits of a certain form
2. run a circuit with a crz gate (qft example from [benchmark repo](https://github.com/latticesurgery-com/benchmark) below, but any rz gate will do)

### Code Snippet

```python

        slices, text = lscp.compile_str(decomposed_qft.qasm(),
                                        simulation_type=lscp.lssim.SimulatorType.NOOP,
                                        apply_litinski_transform=False)
```

The circuit is:
```qasm
Decomposed raw QASM input:
OPENQASM 2.0;
include "qelib1.inc";
qreg q0[3];
u2(0,pi) q0[2];
barrier q0[0],q0[1],q0[2];
rz(pi/4) q0[2];
cx q0[1],q0[2];
rz(-pi/4) q0[2];
cx q0[1],q0[2];
u2(0,pi) q0[1];
barrier q0[0],q0[1],q0[2];
rz(pi/4) q0[1];
rz(pi/8) q0[2];
cx q0[0],q0[2];
rz(-pi/8) q0[2];
cx q0[0],q0[2];
cx q0[0],q0[1];
rz(-pi/4) q0[1];
cx q0[0],q0[1];
u2(0,pi) q0[0];
barrier q0[0],q0[1],q0[2];
```

### Error Output

```
  File "/home/george/projects/latticesurgery-com/benchmark/qft.py", line 35, in <module>
    slices, text = lscp.compile_str(decompose_qft.qasm(),
  File "/home/george/projects/latticesurgery-com/benchmark/external/lattice-surgery-compiler/src/lsqecc/pipeline/lattice_surgery_compilation_pipeline.py", line 77, in compile_str
    logical_computation = llops.LogicalLatticeComputation(input_circuit)
  File "/home/george/projects/latticesurgery-com/benchmark/external/lattice-surgery-compiler/src/lsqecc/logical_lattice_ops/logical_lattice_ops.py", line 100, in __init__
    self._load_circuit()
  File "/home/george/projects/latticesurgery-com/benchmark/external/lattice-surgery-compiler/src/lsqecc/logical_lattice_ops/logical_lattice_ops.py", line 121, in _load_circuit
    reversed(rotations_composer.expand_rotation(current_op))
  File "/home/george/projects/latticesurgery-com/benchmark/external/lattice-surgery-compiler/src/lsqecc/logical_lattice_ops/logical_lattice_ops.py", line 170, in expand_rotation
    raise Exception(
Exception: Unsupported pauli rotation angle pi*1/16

```

**Comment by alexnguyenn** [comment]
Should we switch to parsing with only Qiskit and then do the conversion to Clifford+T?

**Comment by gwwatkin** [comment]
Switchig to parsing with Qiskit only definitely ... we might even be able to do without one day.

Doing the conversion to Clifford+T ourselves is very difficult. It requires implementing the [Solovay-Kitaev](https://michaelnielsen.org/blog/archive/notes/arxiv_0505030_solovay_kitaev.pdf) algorithm which both Qiskit and Quil are struggling to get merged:
 - https://github.com/Qiskit/qiskit-terra/pull/5657
 - https://github.com/quil-lang/quilc/pull/432

The [most popular](https://github.com/search?q=solovay+kitaev) SK implementation on github is [Cryptogoths's](https://github.com/cryptogoth/skc-python), which is already part of Opensurgery. I'm trying it out as a temporary solution. As soon as Qiskit's SK is merged we will switch to that.

Also, only for QFT circuits, it might be possible to get away with some simpler decompositions, that are faster and more accurate than SK. @isolatedinformation  is looking into that and we might handle those separately since it's such a common routine.

**Comment by isolatedinformation** [comment]
These are some of the intersting papers on approximating unitaries.
1. https://arxiv.org/pdf/1212.6253.pdf
2. https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7056491, https://github.com/vadym-kl/sqct/wiki
3. https://arxiv.org/pdf/1403.2975.pdf
4. https://arxiv.org/pdf/2005.05581.pdf

1 uses randomized algorithm under some assumptions, both 2 and 3 use integer factoring as a subroutine, 4 uses a variation of Djikstra's. 2 is avaiable readily on github

**Comment by stylewarning** [comment]
@gwwatkin I expect quilc to be able to do this in an upcoming release, in a few months. Just FYI; happy to keep you updated.

**Comment by gwwatkin** [comment]
@stylewarning , thanks for the update! :slightly_smiling_face:  We ended up using a package called [Gridsynth](https://www.mathstat.dal.ca/~selinger/newsynth/)  (paper is @isolatedinformation 's [link 3](https://arxiv.org/pdf/1403.2975.pdf) I think)

**Comment by gwwatkin** [comment]
I think we can consider the issue closed... we've dealt
