### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#60]
To go here
https://github.com/latticesurgery-com/lattice-surgery-compiler/blob/f0c7b47747aaa235ea7f5c64c5aa929405b6b79e/web/lattice_main/templates/lattice_main/upload_circuit.html#L59

**Comment by Keelando** [comment]
I can set up a gmail address such as lattice.surgery.compiler@gmail.com and set it up to forward emails to any of us. You just have to add it to your safe-sender list. Alternatively, if you have email aliases which can't be used to log in to your account, I can just post those in plain text (less desirable option).

**Comment by Keelando** [comment]
I put a little link to this GitHub at the bottom of the page. I couldn't remember if you had a paper that we should link to? There is an icon in the footer that could link to a paper, preferably one that came from you guys or the department. Could also have a whole page dedicated to the references for "additional reading" :)

**Comment by gwwatkin** [comment]
> I can set up a gmail address such as [lattice.surgery.compiler@gmail.com](mailto:lattice.surgery.compiler@gmail.com) and set it up to forward emails to any of us if people submit their questions. You just have to add it to your safe-sender list. Alternatively, if you have email aliases which can't be used to log in to your account, I can just post those in plain text (less desirable option).

We can have info@latticesurgery.com ... I just need to figure out how to edit the dns records... lets wait a moment before setting up gmail

**Comment by gwwatkin** [comment]
> I put a little link to this GitHub in the footer of the website. I couldn't remember if you had a paper that we should link to? There is an icon in the footer that could link to a paper, preferably one that came from you guys or the department. Could also have a whole page dedicated to the references for "additional reading" :)

Unfortunately we do not have a paper yet :sweat_smile: ... but yes we do need more info on readings and references

**Comment by Keelando** [comment]
Looks like i edited your comment rather than replying to it. You might have read it my comment already, but here it was:


Regarding getting an emailer going, I've spent a lot of effort trying to learn the ropes of emailers and the like. Unless we want to spend $10-15/month for an email service, I have abandoned my dreams of running my own email server. Too much headache. I have found that the gmail solution to be reliable (and free) for getting website updates including inquiries and perhaps critical webapp updates to your own email address. Not a problem for today however

**Comment by gwwatkin** [comment]
We can use @latticesurgery.com emails with another provider, like even gmail. We just need to set up the dns records right.

**Comment by gwwatkin** [comment]
No mail server

**Comment by Keelando** [comment]
Thats awesome. I'll have to learn how to do that for my own websites

**Comment by alexnguyenn** [comment]
Closing since it is not relevant to this repo anymore. Also we are using info@latticesurgery.com now.
