### ISSUE TITLE
Dropdown menu to select example circuits

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#62]
In the circuit upload page, we would like to have a dropdown that has the filenames then when you select on, it uses an ajax call to pull up a visual representation of the circuit.

**Comment by Keelando** [comment]
This feature was partially implemented. Right now the web gui just searches the assets folder for all files (minor oversight that it doesn't explicity target .qasm... will fix that.) and then allows the user to choose from that list. I noticed at one point there was a graphical representation of a circuit getting printed to the shell during the calculation. Is this the visualization you want? It would be pretty easy to render that text in the browser.

**Comment by gwwatkin** [comment]
> This feature was partially implemented. Right now the web gui just searches the assets folder for all files (minor oversight that it doesn't explicity target .qasm... will fix that.) and then allows the user to choose from that list. I noticed at one point there was a graphical representation of a circuit getting printed to the shell during the calculation. Is this the visualization you want? It would be pretty easy to render that text in the browser.

The visualization is back! how it is now is good. Saw you implemented the drop-down. Do you already have an idea of how you would like to visualize the circuit in the upload page? would it show up in a square on the side are you thinking?

If you have the idea you can go ahead and describe it in an issue

**Comment by gwwatkin** [comment]
Searching `compilation_text` will get you to how to draw circuits.
