### ISSUE TITLE
Create dependency DAG of circuit of Pauli rotations operations

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#71]
To be used later by a scheduler to parallelize operations on the lattice. 

Operations that act on different qubits can be parallelized. Need to look into how commuting plays here too. Perhaps things that commute, even when act on the same qubits, should be neighbors in the tree.

**Comment by gwwatkin** [comment]
**Nice to have:** The tree is abstract so it can be reused for logical lattice operations, which sit between  the circuit of Pauli rotations and actual patch operations

**Comment by gwwatkin** [comment]
**Idea:** Start from the back of the circuit (chronologically latest) and work bacwards.
Thinking about it more carefull what we need to construct id a dependency DAG, not a tree
**Example:**
```
Op name:(A)  (B)  (C)  (D)  (E)  (F)
    q1--|X|--|I|--|X|--|I|--|Z|--|I|
    q2--|I|--|Z|--|Z|--|X|--|I|--|Z|
   pi*  1/4  1/4  1/8  1/4   M    M 
```
Tree would look something like:
![DependancyDAG](https://user-images.githubusercontent.com/36427091/113698357-3e02f800-9689-11eb-8539-690aba92231a.png)

Where the thicker circled nodes are terminal and don't depend on anything - they are like the result.

The prototypes could look like so:
```
from typing import *
from circuit import *

T = TypeVar('T')

class DependancyTree: # static class/ namespace

    class Node:
        def __init__(self, op : T, dependencies : List['DependancyTree.Node[T]']):
            self.op = op
            self.dependencies = dependencies

    @staticmethod
    def from_circuit(circuit : Circuit) -> List['DependancyTree.Node[T]']:
    """Returns the list of terminal nodes"""
        pass
```

**Comment by alexnguyenn** [comment]
Since some cases require traversing the tree backwards, we need to keep track of parents as well.

**Comment by gwwatkin** [comment]
It would be interesting to look into the run time analysis of the  algorithm. Intuitively it looks like `O(depth^2)` but there are only so many pauli matrices, so maybe there is a nice counting argument for which we'll always run into a non commuting operator :thinking:

**Comment by alexnguyenn** [comment]
Note: A and B are both commute to C, therefore the above diagram is incorrect.

**Comment by gwwatkin** [comment]
Thanks! Updated the circuit.
