### ISSUE TITLE
Dependency Graph LaTex Drawing

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#88]
Give to each `PauliProductOperation` in the circuit a name like A,B,C .... and then draw the dependency graph:

![Screenshot_20210424_040417](https://user-images.githubusercontent.com/36427091/115956546-38dbe080-a4b2-11eb-9967-3939d9473fb5.png)

This was made with:
```
\usepackage{tikz-cd}

\begin{tikzcd}
 & A\arrow[to=2-3]\arrow[to=2-1] & & &\\
 B\arrow[to=3-1] & & C\arrow[to=3-4] & &\\
 D & & & E\arrow[to=4-3]\arrow[to=4-5]&\\
 & & F& & G\\
\end{tikzcd}
```

**Comment by alexnguyenn** [comment]
This might be complicated since we are no longer referencing to the operations in the circuit with their indices (in the DAG). Also there is the problem of layering the DAG so that `tikz` can render it properly.
